# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'HysteriaPlayerSwiftExample' do
  pod 'HysteriaPlayer',           '~> 2.1.2'
end

target 'HysteriaPlayerSwiftExampleTests' do

end

target 'HysteriaPlayerSwiftExampleUITests' do

end

